# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20180506_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.Category'),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='image_description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictures.Location'),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
