# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20180506_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_description',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
